version: '3.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend_container
    volumes:
      - ./backend:/app
    ports:
      - "8010:8010"  # Map port 8000 in the container to port 8000 on the host
    depends_on:
      - db  # This ensures the db service is started before the backend service
  
  frontend:
    build:
      context: ./frontend # Asegúrate de reemplazar esto con el camino correcto a tu app React
      dockerfile: Dockerfile
    container_name: my_frontend_container
    volumes:
      - ./frontend:/app # Asegúrate de reemplazar esto con el camino correcto a tu app React
    ports:
      - 3010:3010

  db:
    image: mysql:8.0
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: tokyo3
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: icarouscja
      MYSQL_PASSWORD: tokyo3
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: